/**
 * Industrial Finding Codes
 * 
 * Standardized technical codes for the Preflight Engine kernel.
 * These codes are persistent and language-independent.
 */

const CODES = {
    // Geometry & Layout
    GEOM_BLEED_INSUFFICIENT: 'IND_GEOM_001',
    GEOM_BLEED_MISSING: 'IND_GEOM_002',
    GEOM_TRIMBOX_MISSING: 'IND_GEOM_003',
    GEOM_BLEEDBOX_MISSING: 'IND_GEOM_004',
    GEOM_TRIMBOX_INVALID: 'IND_GEOM_005',
    GEOM_TRIMBOX_OUTSIDE_MEDIABOX: 'IND_GEOM_006',
    GEOM_TRIM_MARGIN_WARNING: 'IND_GEOM_007',
    GEOM_TRIM_MARKS_NEAR_LIVE_AREA: 'IND_GEOM_008',
    GEOM_PAGE_SIZE_INCONSISTENT: 'IND_GEOM_009',
    GEOM_PAGE_ROTATION_DETECTED: 'IND_GEOM_010',
    GEOM_MIXED_PAGE_ORIENTATION: 'IND_GEOM_011',
    GEOM_HAIRLINE_DETECTED: 'IND_GEOM_012',

    // Color
    COLOR_RGB_OBJECTS_DETECTED: 'IND_COLOR_001',
    COLOR_ICC_PROFILE_MISSING: 'IND_COLOR_002',
    COLOR_MIXED_COLOR_SPACES: 'IND_COLOR_003',
    COLOR_SPOT_COLOR_DETECTED: 'IND_COLOR_004',
    COLOR_TOTAL_INK_COVERAGE_EXCEEDED: 'IND_COLOR_005',
    COLOR_OUTPUT_INTENT_MISSING: 'IND_COLOR_006',
    COLOR_ICC_PROFILE_MISMATCH: 'IND_COLOR_007',
    COLOR_RICH_BLACK_TEXT: 'IND_COLOR_008',
    COLOR_REGISTRATION_ABUSE: 'IND_COLOR_009',

    // Fonts
    FONT_NOT_EMBEDDED: 'IND_FONT_001',
    FONT_SUBSET: 'IND_FONT_002',
    FONT_TYPE3_FONT_DETECTED: 'IND_FONT_003',
    FONT_GLYPH_MISSING: 'IND_FONT_004',
    // Phase 66A — Font Fixes findings
    FONT_ENCODING_INVALID: 'IND_FONT_005',

    // Images
    IMG_IMAGE_LOW_RESOLUTION: 'IND_IMG_001',
    IMG_IMAGE_EXCESSIVE_RESOLUTION: 'IND_IMG_002',
    IMG_JPEG_ARTIFACTS_DETECTED: 'IND_IMG_003',
    IMG_RGB_IMAGE_DETECTED: 'IND_IMG_004',
    
    // Phase 54A canonical findings
    LOW_RES_IMAGES: 'IND_IMG_005',
    EXCESSIVE_RESOLUTION: 'IND_IMG_006',
    JPEG_ARTIFACTS: 'IND_IMG_007',
    IMAGE_COMPRESSION_RISK: 'IND_IMG_008',
    IMAGE_DOWNSAMPLING_RISK: 'IND_IMG_009',
    IMAGE_UPSCALING_RISK: 'IND_IMG_010',
    IMAGE_REPLACEMENT_REQUIRED: 'IND_IMG_011',
    BITMAP_TEXT_RISK: 'IND_IMG_012',
    RASTERIZED_VECTOR_RISK: 'IND_IMG_013',
    IMAGE_COLORSPACE_RISK: 'IND_IMG_014',
    IMAGE_ALPHA_RISK: 'IND_IMG_015',
    IMAGE_OBJECT_DAMAGED: 'IND_IMG_016',

    // Phase 65A — Selective Image Fixes findings
    RGB_IMAGES_PRESENT: 'IND_IMG_017',
    UNTAGGED_IMAGE: 'IND_IMG_018',
    IMAGE_ICC_MISMATCH: 'IND_IMG_019',
    EXCESSIVE_RESOLUTION_IMAGE: 'IND_IMG_020',

    // Phase 55A Standards Certification
    PDFX_MISSING: 'IND_COMPLIANCE_003',
    PDFX_INVALID: 'IND_COMPLIANCE_004',
    PDFX_CLAIMED_BUT_NOT_VALIDATED: 'IND_COMPLIANCE_005',
    PDFX_METADATA_CONFLICT: 'IND_COMPLIANCE_006',
    PDFA_METADATA_CONFLICT: 'IND_COMPLIANCE_007',
    PDF_STANDARD_UNKNOWN: 'IND_COMPLIANCE_008',
    OUTPUTINTENT_PRESENT_NOT_PDFX: 'IND_COMPLIANCE_009',
    OUTPUTINTENT_MISSING_FOR_STANDARD: 'IND_COMPLIANCE_010',
    OUTPUTINTENT_INVALID_FOR_STANDARD: 'IND_COMPLIANCE_011',
    PDFX_OUTPUTINTENT_CONFLICT: 'IND_COMPLIANCE_012',
    STANDARD_VALIDATOR_UNAVAILABLE: 'IND_COMPLIANCE_013',
    STANDARD_VALIDATION_FAILED: 'IND_COMPLIANCE_014',
    STANDARD_VALIDATION_REQUIRED: 'IND_COMPLIANCE_015',
    CERTIFIED_PDF_NOT_STANDARD_CERTIFIED: 'IND_COMPLIANCE_016',
    PRODUCTION_CERTIFIED_WITHOUT_STANDARD_VALIDATION: 'IND_COMPLIANCE_017',
    PDFX_TRANSPARENCY_CONFLICT: 'IND_COMPLIANCE_018',
    PDFX_FONT_CONFLICT: 'IND_COMPLIANCE_019',
    PDFX_COLOR_CONFLICT: 'IND_COMPLIANCE_020',
    PDFX_IMAGE_CONFLICT: 'IND_COMPLIANCE_021',
    STANDARD_CLAIM_WITHOUT_VALIDATOR_EVIDENCE: 'IND_COMPLIANCE_022',

    // Phase 68A — Real PDF/X / PDF/A Validator Integration
    PDFA_MISSING: 'IND_COMPLIANCE_023',
    PDFA_INVALID: 'IND_COMPLIANCE_024',
    PDFA_CLAIMED_BUT_NOT_VALIDATED: 'IND_COMPLIANCE_025',
    STANDARD_VALIDATION_PASSED: 'IND_COMPLIANCE_026',
    VALIDATOR_EVIDENCE_COMPLETE: 'IND_COMPLIANCE_027',
    VALIDATOR_EVIDENCE_INCOMPLETE: 'IND_COMPLIANCE_028',

    // Transparency
    TRANS_TRANSPARENCY_DETECTED: 'IND_TRANS_001',
    TRANS_BLEND_MODE_DETECTED: 'IND_TRANS_002',
    TRANS_SOFT_MASK_DETECTED: 'IND_TRANS_003',
    TRANSPARENCY_PRESENT: 'IND_TRANS_004',
    TRANSPARENCY_GROUPS: 'IND_TRANS_005',
    SOFT_MASK_PRESENT: 'IND_TRANS_006',
    BLEND_MODE_PRESENT: 'IND_TRANS_007',
    KNOCKOUT_GROUP_PRESENT: 'IND_TRANS_008',
    RASTERIZATION_RISK: 'IND_TRANS_009',

    // Overprint
    OVERPRINT_DETECTED: 'IND_OVERPRINT_001',
    OVERPRINT_KNOCKOUT_CONFLICT: 'IND_OVERPRINT_002',
    OVERPRINT_PRESENT: 'IND_OVERPRINT_003',
    OVERPRINT_MODE_PRESENT: 'IND_OVERPRINT_004',

    // Marks
    MARK_CROP_MARKS_MISSING: 'IND_MARK_001',
    MARK_REGISTRATION_MARKS_PRESENT: 'IND_MARK_002',
    MARK_COLOR_BAR_DETECTED: 'IND_MARK_003',
    CROP_MARKS_MISSING: 'IND_MARK_004',
    CROP_MARKS_INVALID: 'IND_MARK_005',
    CROP_MARKS_OUTSIDE_SAFE_ZONE: 'IND_MARK_006',
    REGISTRATION_MARKS_PRESENT: 'IND_MARK_007',
    REGISTRATION_MARKS_INSIDE_TRIM: 'IND_MARK_008',
    REGISTRATION_MARKS_OUTSIDE_TRIM: 'IND_MARK_009',
    PAGE_MARKS_INCONSISTENT: 'IND_MARK_010',
    PAGE_MARKS_UNCERTAIN_GEOMETRY: 'IND_MARK_011',
    TRIMBOX_REQUIRED_FOR_MARKS: 'IND_MARK_012',
    INSUFFICIENT_MARGIN_FOR_CROP_MARKS: 'IND_MARK_013',

    // PDF/X Compliance
    COMPLIANCE_PDFX_MISSING: 'IND_COMPLIANCE_001',
    COMPLIANCE_PDFX_INVALID: 'IND_COMPLIANCE_002',

    // Phase 64A — Ink / TAC / Black / Registration Color findings
    INK_TOTAL_COVERAGE_EXCESSIVE: 'IND_INK_001',
    INK_RICH_BLACK_TEXT: 'IND_INK_002',
    INK_SMALL_TEXT_RICH_BLACK: 'IND_INK_003',
    INK_REGISTRATION_COLOR_MISUSE: 'IND_INK_004',
    INK_BLACK_TEXT_NOT_K_ONLY: 'IND_INK_005',

    // Phase 63A — PDF Security / Interactive Object findings
    PDF_JAVASCRIPT_PRESENT: 'IND_SEC_001',
    PDF_LAUNCH_ACTION_PRESENT: 'IND_SEC_002',
    PDF_EMBEDDED_FILES_PRESENT: 'IND_SEC_003',
    PDF_DOCUMENT_OPEN_ACTION_PRESENT: 'IND_SEC_004',
    PDF_PAGE_OPEN_ACTION_PRESENT: 'IND_SEC_005',
    PDF_ANNOTATIONS_PRESENT: 'IND_SEC_006',
    PDF_ACROFORMS_PRESENT: 'IND_SEC_007',
    PDF_XFA_FORMS_PRESENT: 'IND_SEC_008',
    PDF_INTERACTIVE_CONTENT_PRESENT: 'IND_SEC_009',
    PDF_ACTIVE_CONTENT_PRESENT: 'IND_SEC_010',
    PDF_SECURITY_CLEANUP_REQUIRED: 'IND_SEC_011',
    ANNOTATION_FLATTENING_REQUIRED: 'IND_SEC_012',
    FORM_FLATTENING_REQUIRED: 'IND_SEC_013',
    INTERACTIVE_CONTENT_UNSAFE_TO_FLATTEN: 'IND_SEC_014',
    PDF_ACTIONS_PRESENT: 'IND_SEC_015',
    PDF_UNSAFE_INTERACTIVE_OBJECTS: 'IND_SEC_016',

    // Structural & Forensic
    STRUCT_ANNOTATIONS_DETECTED: 'IND_STRUCT_001',
    STRUCT_ACROFORM_DETECTED: 'IND_STRUCT_002',
    STRUCT_JAVASCRIPT_DETECTED: 'IND_STRUCT_003',
    STRUCT_XREF_BROKEN: 'IND_STRUCT_004',
    STRUCT_OBJECT_STREAM_ANOMALY: 'IND_STRUCT_005',
    OBJECT_STREAMS_PRESENT: 'IND_STRUCT_006',
    OBJECT_STREAMS_INCONSISTENT: 'IND_STRUCT_007',
    PDF_STRUCTURE_NEEDS_NORMALIZATION: 'IND_STRUCT_008',

    // Document Classification
    TYPE_UNKNOWN: 'IND_TYPE_000',
    TYPE_FLYER: 'IND_TYPE_001',
    TYPE_POSTER: 'IND_TYPE_002',
    TYPE_BROCHURE: 'IND_TYPE_003',
    TYPE_BOOK_INTERIOR: 'IND_TYPE_004',
    TYPE_MAGAZINE: 'IND_TYPE_005',

    // Technical Status
    TECH_EXEC_FAILED: 'IND_TECH_999'
};

module.exports = { CODES };
