/**
 * Industrial Finding Codes
 * 
 * Standardized technical codes for the Preflight Engine kernel.
 * These codes are persistent and language-independent.
 */

const CODES = {
    // Geometry & Layout
    GEOM_BLEED_INSUFFICIENT: 'IND_GEOM_001',
    GEOM_BLEED_MISSING: 'IND_GEOM_002',
    GEOM_TRIMBOX_MISSING: 'IND_GEOM_003',
    GEOM_BLEEDBOX_MISSING: 'IND_GEOM_004',
    GEOM_TRIMBOX_INVALID: 'IND_GEOM_005',
    GEOM_TRIMBOX_OUTSIDE_MEDIABOX: 'IND_GEOM_006',
    GEOM_TRIM_MARGIN_WARNING: 'IND_GEOM_007',
    GEOM_TRIM_MARKS_NEAR_LIVE_AREA: 'IND_GEOM_008',
    GEOM_PAGE_SIZE_INCONSISTENT: 'IND_GEOM_009',
    GEOM_PAGE_ROTATION_DETECTED: 'IND_GEOM_010',
    GEOM_MIXED_PAGE_ORIENTATION: 'IND_GEOM_011',
    GEOM_HAIRLINE_DETECTED: 'IND_GEOM_012',

    // Color
    COLOR_RGB_OBJECTS_DETECTED: 'IND_COLOR_001',
    COLOR_ICC_PROFILE_MISSING: 'IND_COLOR_002',
    COLOR_MIXED_COLOR_SPACES: 'IND_COLOR_003',
    COLOR_SPOT_COLOR_DETECTED: 'IND_COLOR_004',
    COLOR_TOTAL_INK_COVERAGE_EXCEEDED: 'IND_COLOR_005',
    COLOR_OUTPUT_INTENT_MISSING: 'IND_COLOR_006',
    COLOR_ICC_PROFILE_MISMATCH: 'IND_COLOR_007',
    COLOR_RICH_BLACK_TEXT: 'IND_COLOR_008',
    COLOR_REGISTRATION_ABUSE: 'IND_COLOR_009',

    // Fonts
    FONT_NOT_EMBEDDED: 'IND_FONT_001',
    FONT_SUBSET: 'IND_FONT_002',
    FONT_TYPE3_FONT_DETECTED: 'IND_FONT_003',
    FONT_GLYPH_MISSING: 'IND_FONT_004',

    // Images
    IMG_IMAGE_LOW_RESOLUTION: 'IND_IMG_001',
    IMG_IMAGE_EXCESSIVE_RESOLUTION: 'IND_IMG_002',
    IMG_JPEG_ARTIFACTS_DETECTED: 'IND_IMG_003',
    IMG_RGB_IMAGE_DETECTED: 'IND_IMG_004',
    
    // Phase 54A canonical findings
    LOW_RES_IMAGES: 'IND_IMG_005',
    EXCESSIVE_RESOLUTION: 'IND_IMG_006',
    JPEG_ARTIFACTS: 'IND_IMG_007',
    IMAGE_COMPRESSION_RISK: 'IND_IMG_008',
    IMAGE_DOWNSAMPLING_RISK: 'IND_IMG_009',
    IMAGE_UPSCALING_RISK: 'IND_IMG_010',
    IMAGE_REPLACEMENT_REQUIRED: 'IND_IMG_011',
    BITMAP_TEXT_RISK: 'IND_IMG_012',
    RASTERIZED_VECTOR_RISK: 'IND_IMG_013',
    IMAGE_COLORSPACE_RISK: 'IND_IMG_014',
    IMAGE_ALPHA_RISK: 'IND_IMG_015',
    IMAGE_OBJECT_DAMAGED: 'IND_IMG_016',

    // Transparency
    TRANS_TRANSPARENCY_DETECTED: 'IND_TRANS_001',
    TRANS_BLEND_MODE_DETECTED: 'IND_TRANS_002',
    TRANS_SOFT_MASK_DETECTED: 'IND_TRANS_003',
    TRANSPARENCY_PRESENT: 'IND_TRANS_004',
    TRANSPARENCY_GROUPS: 'IND_TRANS_005',
    SOFT_MASK_PRESENT: 'IND_TRANS_006',
    BLEND_MODE_PRESENT: 'IND_TRANS_007',
    KNOCKOUT_GROUP_PRESENT: 'IND_TRANS_008',
    RASTERIZATION_RISK: 'IND_TRANS_009',

    // Overprint
    OVERPRINT_DETECTED: 'IND_OVERPRINT_001',
    OVERPRINT_KNOCKOUT_CONFLICT: 'IND_OVERPRINT_002',
    OVERPRINT_PRESENT: 'IND_OVERPRINT_003',
    OVERPRINT_MODE_PRESENT: 'IND_OVERPRINT_004',

    // Marks
    MARK_CROP_MARKS_MISSING: 'IND_MARK_001',
    MARK_REGISTRATION_MARKS_PRESENT: 'IND_MARK_002',
    MARK_COLOR_BAR_DETECTED: 'IND_MARK_003',

    // PDF/X Compliance
    COMPLIANCE_PDFX_MISSING: 'IND_COMPLIANCE_001',
    COMPLIANCE_PDFX_INVALID: 'IND_COMPLIANCE_002',

    // Structural & Forensic
    STRUCT_ANNOTATIONS_DETECTED: 'IND_STRUCT_001',
    STRUCT_ACROFORM_DETECTED: 'IND_STRUCT_002',
    STRUCT_JAVASCRIPT_DETECTED: 'IND_STRUCT_003',
    STRUCT_XREF_BROKEN: 'IND_STRUCT_004',
    STRUCT_OBJECT_STREAM_ANOMALY: 'IND_STRUCT_005',

    // Document Classification
    TYPE_UNKNOWN: 'IND_TYPE_000',
    TYPE_FLYER: 'IND_TYPE_001',
    TYPE_POSTER: 'IND_TYPE_002',
    TYPE_BROCHURE: 'IND_TYPE_003',
    TYPE_BOOK_INTERIOR: 'IND_TYPE_004',
    TYPE_MAGAZINE: 'IND_TYPE_005',

    // Technical Status
    TECH_EXEC_FAILED: 'IND_TECH_999'
};

module.exports = { CODES };
