/**
 * Industrial Finding Codes
 * 
 * Standardized technical codes for the Preflight Engine kernel.
 * These codes are persistent and language-independent.
 */

const CODES = {
    // Geometry & Layout
    GEOM_BLEED_INSUFFICIENT: 'IND_GEOM_001',
    GEOM_BLEED_MISSING: 'IND_GEOM_002',
    GEOM_TRIMBOX_MISSING: 'IND_GEOM_003',
    GEOM_BLEEDBOX_MISSING: 'IND_GEOM_004',
    GEOM_TRIMBOX_INVALID: 'IND_GEOM_005',
    GEOM_TRIMBOX_OUTSIDE_MEDIABOX: 'IND_GEOM_006',
    GEOM_TRIM_MARGIN_WARNING: 'IND_GEOM_007',
    GEOM_TRIM_MARKS_NEAR_LIVE_AREA: 'IND_GEOM_008',
    GEOM_PAGE_SIZE_INCONSISTENT: 'IND_GEOM_009',
    GEOM_PAGE_ROTATION_DETECTED: 'IND_GEOM_010',
    GEOM_MIXED_PAGE_ORIENTATION: 'IND_GEOM_011',

    // Color
    COLOR_RGB_OBJECTS_DETECTED: 'IND_COLOR_001',
    COLOR_ICC_PROFILE_MISSING: 'IND_COLOR_002',
    COLOR_MIXED_COLOR_SPACES: 'IND_COLOR_003',
    COLOR_SPOT_COLOR_DETECTED: 'IND_COLOR_004',
    COLOR_TOTAL_INK_COVERAGE_EXCEEDED: 'IND_COLOR_005',

    // Fonts
    FONT_NOT_EMBEDDED: 'IND_FONT_001',
    FONT_SUBSET: 'IND_FONT_002',
    FONT_TYPE3_FONT_DETECTED: 'IND_FONT_003',
    FONT_GLYPH_MISSING: 'IND_FONT_004',

    // Images
    IMG_IMAGE_LOW_RESOLUTION: 'IND_IMG_001',
    IMG_IMAGE_EXCESSIVE_RESOLUTION: 'IND_IMG_002',
    IMG_JPEG_ARTIFACTS_DETECTED: 'IND_IMG_003',

    // Transparency
    TRANS_TRANSPARENCY_DETECTED: 'IND_TRANS_001',
    TRANS_BLEND_MODE_DETECTED: 'IND_TRANS_002',

    // Overprint
    OVERPRINT_DETECTED: 'IND_OVERPRINT_001',
    OVERPRINT_KNOCKOUT_CONFLICT: 'IND_OVERPRINT_002',

    // Marks
    MARK_CROP_MARKS_MISSING: 'IND_MARK_001',
    MARK_REGISTRATION_MARKS_PRESENT: 'IND_MARK_002',
    MARK_COLOR_BAR_DETECTED: 'IND_MARK_003',

    // Document Classification
    TYPE_UNKNOWN: 'IND_TYPE_000',
    TYPE_FLYER: 'IND_TYPE_001',
    TYPE_POSTER: 'IND_TYPE_002',
    TYPE_BROCHURE: 'IND_TYPE_003',
    TYPE_BOOK_INTERIOR: 'IND_TYPE_004',
    TYPE_MAGAZINE: 'IND_TYPE_005',

    // Technical Status
    TECH_EXEC_FAILED: 'IND_TECH_999'
};

module.exports = { CODES };
