const REGISTRY = {
    // Existing implemented/partial fixes
    "REBUILD_TRIMBOX": {
        fix_id: "REBUILD_TRIMBOX",
        label: "Rebuild TrimBox",
        category: "geometry",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: false,
        production_safe: true,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Document TrimBox was successfully rebuilt to standard production geometry.",
        operator_message: "TrimBox rebuilt based on MediaBox/production inference."
    },
    "APPLY_BLEED": {
        fix_id: "APPLY_BLEED",
        label: "Apply bleed box expansion",
        category: "geometry",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Bleed box was expanded, but artwork was not visually extended.",
        operator_message: "Bleed box expansion only; true artwork bleed extension is not currently supported."
    },
    "CONVERT_CMYK": {
        fix_id: "CONVERT_CMYK",
        label: "Convert to CMYK",
        category: "color",
        implemented: true,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["Ghostscript"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Colorspace was converted to CMYK. Colors may shift.",
        operator_message: "Destructive CMYK conversion applied via Ghostscript."
    },
    "INJECT_OUTPUT_INTENT": {
        fix_id: "INJECT_OUTPUT_INTENT",
        label: "Inject OutputIntent",
        category: "color",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW", // Medium if profile mismatch or PDF/X claim is made
        requires_human_review: false,
        production_safe: true,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Standard production color profile was injected.",
        operator_message: "OutputIntent with ICC profile injected into PDF catalog.",
        compliance_claim_allowed: false,
        validator_required: false,
        validator_available: false,
        standard_claimed: null
    },
    "NORMALIZE_ICC_PROFILE": {
        fix_id: "NORMALIZE_ICC_PROFILE",
        label: "Normalize ICC Profile",
        category: "color",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "ICC Profile normalization is currently not supported.",
        operator_message: "ICC Profile normalization is currently scaffolded."
    },
    "REDUCE_TAC": {
        fix_id: "REDUCE_TAC",
        label: "Reduce Total Area Coverage",
        category: "color",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Ink coverage reduction is currently not supported.",
        operator_message: "TAC reduction is currently scaffolded."
    },

    // Phase 63A — PDF Security / Interactive Object Safe Fixes
    "STRIP_JAVASCRIPT": {
        fix_id: "STRIP_JAVASCRIPT",
        label: "Strip JavaScript",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "JavaScript actions were neutralized to ensure print safety.",
        operator_message: "Removed catalog OpenAction and JavaScript names.",
        security_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "REMOVE_LAUNCH_ACTIONS": {
        fix_id: "REMOVE_LAUNCH_ACTIONS",
        label: "Remove launch actions",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Launch actions were removed to ensure print safety.",
        operator_message: "Removed /Launch actions from catalog, pages, and annotations.",
        security_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "REMOVE_EMBEDDED_FILES": {
        fix_id: "REMOVE_EMBEDDED_FILES",
        label: "Remove embedded files",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Embedded files were removed to ensure print safety.",
        operator_message: "Removed Names/EmbeddedFiles entries and associated file specifications.",
        security_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "REMOVE_DOCUMENT_OPEN_ACTIONS": {
        fix_id: "REMOVE_DOCUMENT_OPEN_ACTIONS",
        label: "Remove document open actions",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Document-open actions were removed to ensure print safety.",
        operator_message: "Removed catalog /OpenAction and document-level /AA entries.",
        security_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "REMOVE_PAGE_OPEN_ACTIONS": {
        fix_id: "REMOVE_PAGE_OPEN_ACTIONS",
        label: "Remove page open actions",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Page-open actions were removed to ensure print safety.",
        operator_message: "Removed page-level /AA (additional actions) entries.",
        security_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "FLATTEN_ANNOTATIONS": {
        fix_id: "FLATTEN_ANNOTATIONS",
        label: "Flatten annotations",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Interactive annotations were flattened into the PDF structure.",
        operator_message: "Annotation references removed to reduce print-production risk.",
        security_sensitive: true,
        visually_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },
    "FLATTEN_FORMS": {
        fix_id: "FLATTEN_FORMS",
        label: "Flatten forms",
        category: "pdf_security_interactivity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Interactive forms were flattened into the PDF structure.",
        operator_message: "AcroForm fields flattened to reduce print-production risk.",
        security_sensitive: true,
        visually_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        standard_certified: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        production_certified: false
    },

    // Page Marks Fixes
    "ADD_CROP_MARKS": {
        fix_id: "ADD_CROP_MARKS",
        label: "Add crop marks",
        category: "page_marks",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Crop marks were added outside the trim area.",
        operator_message: "Added crop marks outside TrimBox.",
        visually_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        standard_certified: false
    },
    "REMOVE_REGISTRATION_MARKS": {
        fix_id: "REMOVE_REGISTRATION_MARKS",
        label: "Remove registration marks",
        category: "page_marks",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Registration marks were removed from the document.",
        operator_message: "Removed registration marks outside TrimBox.",
        visually_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        standard_certified: false
    },
    "NORMALIZE_PAGE_MARKS": {
        fix_id: "NORMALIZE_PAGE_MARKS",
        label: "Normalize page marks",
        category: "page_marks",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Page marks metadata was normalized.",
        operator_message: "Normalized page marks diagnostics and metadata.",
        visually_sensitive: true,
        evidence_required: true,
        compliance_claim_allowed: false,
        pdfx_compliance_claimed: false,
        pdfa_compliance_claimed: false,
        standard_certified: false
    },

    "REBUILD_XREF": {
        fix_id: "REBUILD_XREF",
        label: "Rebuild XREF",
        category: "structure",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: false,
        production_safe: true,
        destructive: false,
        toolchain: ["qpdf"],
        supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "PDF structure was sanitized for optimal compatibility.",
        operator_message: "Structural sanitization attempted via qpdf."
    },
    "NORMALIZE_OBJECT_STREAMS": {
        fix_id: "NORMALIZE_OBJECT_STREAMS",
        label: "Normalize object streams",
        category: "structural_integrity",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: false,
        production_safe: true,
        destructive: false,
        toolchain: ["qpdf"],
        supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "PDF structure was normalized for optimal compatibility.",
        operator_message: "Object stream normalization attempted via qpdf.",
        evidence_required: true
    },

    // Medium/high-risk scaffolding, not necessarily implemented yet
    "FLATTEN_TRANSPARENCY": {
        fix_id: "FLATTEN_TRANSPARENCY",
        label: "Flatten transparency",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Transparency flattening is currently not supported.",
        operator_message: "Transparency flattening is currently scaffolded."
    },
    "FLATTEN_PDF": {
        fix_id: "FLATTEN_PDF",
        label: "Flatten PDF",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "PDF flattening is currently not supported.",
        operator_message: "PDF flattening is currently scaffolded."
    },
    "FLATTEN_OVERPRINT": {
        fix_id: "FLATTEN_OVERPRINT",
        label: "Flatten overprint",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "CRITICAL",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Overprint flattening is currently not supported.",
        operator_message: "Overprint flattening is currently scaffolded."
    },
    "NORMALIZE_OVERPRINT": {
        fix_id: "NORMALIZE_OVERPRINT",
        label: "Normalize overprint",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Overprint normalization is currently not supported.",
        operator_message: "Overprint normalization is currently scaffolded."
    },
    "REMOVE_SOFT_MASKS": {
        fix_id: "REMOVE_SOFT_MASKS",
        label: "Remove soft masks",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Soft mask removal is currently not supported.",
        operator_message: "Soft mask removal is currently scaffolded."
    },
    "RASTERIZE_TRANSPARENCY": {
        fix_id: "RASTERIZE_TRANSPARENCY",
        label: "Rasterize transparency",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Transparency rasterization is currently not supported.",
        operator_message: "Transparency rasterization is currently scaffolded."
    },
    "CONVERT_TO_PDFX_TRANSPARENCY_SAFE": {
        fix_id: "CONVERT_TO_PDFX_TRANSPARENCY_SAFE",
        label: "Convert to PDF/X Transparency Safe",
        category: "transparency_overprint",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "PDF/X conversion for transparency is currently not supported.",
        operator_message: "PDF/X conversion for transparency is currently scaffolded."
    },
    "EMBED_FONTS": {
        fix_id: "EMBED_FONTS",
        label: "Embed fonts",
        category: "font_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: ["ghostscript"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Font embedding may alter glyph rendering and requires human review.",
        operator_message: "Font embedding is only attempted via Ghostscript when a usable font source is available; returns SKIPPED_UNAVAILABLE_FONT_SOURCE otherwise. Never invents glyphs.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "OUTLINE_FONTS": {
        fix_id: "OUTLINE_FONTS",
        label: "Outline fonts",
        category: "fonts",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Font outlining is currently not supported.",
        operator_message: "Font outlining is currently scaffolded."
    },
    "REPLACE_MISSING_FONTS": {
        fix_id: "REPLACE_MISSING_FONTS",
        label: "Replace missing fonts",
        category: "fonts",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Missing font replacement is currently not supported.",
        operator_message: "Missing font replacement is currently scaffolded."
    },
    "GLYPH_REPAIR": {
        fix_id: "GLYPH_REPAIR",
        label: "Glyph repair",
        category: "fonts",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Glyph repair is currently not supported.",
        operator_message: "Glyph repair is currently scaffolded."
    },
    // Phase 66A — Engine Font Fixes (font_governance)
    "SUBSET_EMBEDDED_FONTS": {
        fix_id: "SUBSET_EMBEDDED_FONTS",
        label: "Subset embedded fonts",
        category: "font_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: ["ghostscript"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Font subsetting may affect glyph coverage and requires human review.",
        operator_message: "Subsetting embedded fonts can drop glyphs needed for later edits or reflow; only attempted via Ghostscript when a font source is available, with before/after evidence. Returns SKIPPED_UNAVAILABLE_FONT_SOURCE otherwise.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "OUTLINE_TYPE3_FONTS": {
        fix_id: "OUTLINE_TYPE3_FONTS",
        label: "Outline Type 3 fonts",
        category: "font_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: ["ghostscript"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Converting Type 3 fonts to outlines may affect text appearance and requires human review.",
        operator_message: "Type 3 fonts are bitmap/procedure-based glyph definitions; converting them to vector outlines changes rendering and is destructive. Requires evidence-backed visual review and is never auto-applied.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "REPAIR_FONT_ENCODING": {
        fix_id: "REPAIR_FONT_ENCODING",
        label: "Repair font encoding",
        category: "font_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: ["ghostscript", "qpdf", "mutool"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Font encoding repair may change which characters render and requires human review.",
        operator_message: "Repairing a font's encoding/CMap can change glyph-to-character mapping; an incorrect repair would silently corrupt text. Requires evidence-backed mapping and human review; never guessed.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "FLAG_MISSING_GLYPHS_UNFIXABLE": {
        fix_id: "FLAG_MISSING_GLYPHS_UNFIXABLE",
        label: "Flag missing glyphs as unfixable",
        category: "font_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: false,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Missing glyphs have been flagged for review; they cannot be safely invented automatically.",
        operator_message: "Detection/flagging only — missing glyphs cannot be invented or substituted without source font data and customer approval. No font/glyph synthesis is ever performed.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    // Phase 55A: Standards Certification Capabilities
    "VALIDATE_PDFX": {
        fix_id: "VALIDATE_PDFX",
        label: "Validate PDF/X",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "PDF/X validation is currently not supported without a real validator.",
        operator_message: "PDF/X validation is currently scaffolded. Real validator evidence is required.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "VALIDATE_PDFA": {
        fix_id: "VALIDATE_PDFA",
        label: "Validate PDF/A",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "PDF/A validation is currently not supported without a real validator.",
        operator_message: "PDF/A validation is currently scaffolded. Real validator evidence is required.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "CONVERT_TO_PDFX": {
        fix_id: "CONVERT_TO_PDFX",
        label: "Convert to PDF/X",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "PDF/X conversion is currently not supported without real conversion and validation.",
        operator_message: "PDF/X conversion is currently scaffolded.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "GENERATE_PDFX": {
        fix_id: "GENERATE_PDFX",
        label: "Generate PDF/X",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "PDF/X generation is currently not supported without real conversion and validation.",
        operator_message: "Alias for CONVERT_TO_PDFX. Scaffolded.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "CONVERT_TO_PDFA": {
        fix_id: "CONVERT_TO_PDFA",
        label: "Convert to PDF/A",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "PDF/A conversion is currently not supported without real conversion and validation.",
        operator_message: "PDF/A conversion is currently scaffolded.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "STRIP_INVALID_PDFX_METADATA": {
        fix_id: "STRIP_INVALID_PDFX_METADATA",
        label: "Strip invalid PDF/X metadata",
        category: "standards_certification",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Invalid PDF/X metadata was stripped.",
        operator_message: "Stripped invalid PDF/X metadata.",
        compliance_claim_allowed: false,
        pdfx_compliance_claimed: false,
        standard_certified: false,
        validator_required: false,
        validator_available: false,
        evidence_required: true,
        standard_claimed: null
    },
    "STRIP_INVALID_PDFA_METADATA": {
        fix_id: "STRIP_INVALID_PDFA_METADATA",
        label: "Strip invalid PDF/A metadata",
        category: "standards_certification",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Invalid PDF/A metadata was stripped.",
        operator_message: "Stripped invalid PDF/A metadata.",
        compliance_claim_allowed: false,
        pdfa_compliance_claimed: false,
        standard_certified: false,
        validator_required: false,
        validator_available: false,
        evidence_required: true,
        standard_claimed: null
    },
    "NORMALIZE_STANDARD_METADATA": {
        fix_id: "NORMALIZE_STANDARD_METADATA",
        label: "Normalize standard metadata",
        category: "standards_certification",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Standard metadata was normalized.",
        operator_message: "Normalized standard metadata to an honest non-certified state.",
        compliance_claim_allowed: false,
        standard_certified: false,
        validator_required: false,
        validator_available: false,
        evidence_required: true,
        standard_claimed: null
    },
    "REPAIR_PDFX_OUTPUTINTENT": {
        fix_id: "REPAIR_PDFX_OUTPUTINTENT",
        label: "Repair PDF/X OutputIntent",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Repairing PDF/X OutputIntent is currently not supported.",
        operator_message: "Repairing PDF/X OutputIntent is currently scaffolded.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "MARK_STANDARD_UNCERTIFIED": {
        fix_id: "MARK_STANDARD_UNCERTIFIED",
        label: "Mark standard uncertified",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Marking standard as uncertified is currently not supported.",
        operator_message: "Governance action scaffolded.",
        compliance_claim_allowed: false,
        validator_required: false,
        validator_available: false,
        standard_claimed: null
    },
    "REVOKE_FALSE_CERTIFICATION": {
        fix_id: "REVOKE_FALSE_CERTIFICATION",
        label: "Revoke false certification",
        category: "standards_certification",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: ["pdf-lib"],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "False standards certification claims were revoked.",
        operator_message: "Revoked false standards certification claims.",
        compliance_claim_allowed: false,
        standard_certified: false,
        validator_required: false,
        validator_available: false,
        evidence_required: true,
        standard_claimed: null
    },
    "GENERATE_STANDARD_VALIDATION_REPORT": {
        fix_id: "GENERATE_STANDARD_VALIDATION_REPORT",
        label: "Generate standard validation report",
        category: "standards_certification",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Generating standard validation report is currently not supported.",
        operator_message: "Scaffolded. Requires real validator evidence.",
        compliance_claim_allowed: false,
        validator_required: true,
        validator_available: false,
        standard_claimed: null
    },
    "GENERATE_STANDARD_VALIDATION_REPORT_INTERNAL": {
        fix_id: "GENERATE_STANDARD_VALIDATION_REPORT_INTERNAL",
        label: "Generate internal standard validation report",
        category: "standards_certification",
        implemented: true,
        detectable: true,
        autofixable: true,
        risk_level: "LOW",
        requires_human_review: false,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Internal standards governance report was generated.",
        operator_message: "Generated internal governance report. Not an external validator report.",
        compliance_claim_allowed: false,
        standard_certified: false,
        validator_required: false,
        validator_available: false,
        evidence_required: true,
        standard_claimed: null
    },
    // Phase 64A — Ink / TAC / Black / Registration Color Fixes
    "DETECT_TOTAL_INK_COVERAGE": {
        fix_id: "DETECT_TOTAL_INK_COVERAGE",
        label: "Detect total ink coverage",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "LOW",
        requires_human_review: false,
        production_safe: false,
        destructive: false,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Total ink coverage detection is currently not supported.",
        operator_message: "Total ink coverage detection is currently scaffolded.",
        visually_sensitive: false,
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false
    },
    "REDUCE_TOTAL_INK_COVERAGE": {
        fix_id: "REDUCE_TOTAL_INK_COVERAGE",
        label: "Reduce total ink coverage",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Ink coverage reduction may affect color appearance and requires human review.",
        operator_message: "TAC reduction is visually destructive; no safe physical reduction is available without a rendering pipeline.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "MAP_RICH_BLACK_TEXT_TO_K_ONLY": {
        fix_id: "MAP_RICH_BLACK_TEXT_TO_K_ONLY",
        label: "Map rich black text to K-only",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Rich black text mapping may affect appearance and requires human review.",
        operator_message: "Mapping rich black text to K-only requires color content stream editing; scaffolded only.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "MAP_REGISTRATION_COLOR_TO_BLACK": {
        fix_id: "MAP_REGISTRATION_COLOR_TO_BLACK",
        label: "Map registration color to black",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Registration color mapping may affect appearance and requires human review.",
        operator_message: "Mapping registration color to black requires color content stream editing; scaffolded only.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "NORMALIZE_BLACK_TEXT": {
        fix_id: "NORMALIZE_BLACK_TEXT",
        label: "Normalize black text to K-only",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Black text normalization may affect appearance and requires human review.",
        operator_message: "Normalizing black text to K-only requires color content stream editing; scaffolded only.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "DETECT_SMALL_TEXT_RICH_BLACK": {
        fix_id: "DETECT_SMALL_TEXT_RICH_BLACK",
        label: "Detect small text using rich black",
        category: "ink_governance",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Small text with rich black has been flagged for review; resolution requires human correction.",
        operator_message: "Detection only — physical correction of small rich-black text cannot be safely automated.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "OPTIMIZE_EXCESSIVE_IMAGE_RESOLUTION": {
        fix_id: "OPTIMIZE_EXCESSIVE_IMAGE_RESOLUTION",
        label: "Optimize excessive image resolution",
        category: "images",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Image resolution optimization is currently not supported.",
        operator_message: "Image resolution optimization is currently scaffolded."
    },
    "VISUAL_BLEED_EXTENSION": {
        fix_id: "VISUAL_BLEED_EXTENSION",
        label: "Visual bleed extension",
        category: "geometry",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Visual bleed extension is currently not supported.",
        operator_message: "Visual bleed extension is currently scaffolded."
    },
    // Phase 54A Image Quality
    "UPSCALE_LOW_RES_IMAGES": {
        fix_id: "UPSCALE_LOW_RES_IMAGES",
        label: "Upscale low resolution images",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Image upscaling is currently not supported.",
        operator_message: "upscaling/interpolation may create artificial detail and cannot restore true image quality."
    },
    "DOWNSAMPLE_EXCESSIVE_RESOLUTION": {
        fix_id: "DOWNSAMPLE_EXCESSIVE_RESOLUTION",
        label: "Downsample excessive resolution",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Image downsampling is currently not supported.",
        operator_message: "downsampling can remove visual detail."
    },
    "RECOMPRESS_IMAGES": {
        fix_id: "RECOMPRESS_IMAGES",
        label: "Recompress images",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Image recompression is currently not supported.",
        operator_message: "recompression can introduce artifacts."
    },
    "REPLACE_LOW_RES_IMAGES": {
        fix_id: "REPLACE_LOW_RES_IMAGES",
        label: "Replace low resolution images",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Image replacement is currently not supported.",
        operator_message: "replacement requires source assets/customer approval."
    },
    "REPAIR_JPEG_ARTIFACTS": {
        fix_id: "REPAIR_JPEG_ARTIFACTS",
        label: "Repair JPEG artifacts",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "JPEG artifact repair is currently not supported.",
        operator_message: "JPEG artifact repair is unsupported."
    },
    "NORMALIZE_IMAGE_COLORSPACE": {
        fix_id: "NORMALIZE_IMAGE_COLORSPACE",
        label: "Normalize image colorspace",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Image colorspace normalization is currently not supported.",
        operator_message: "Image colorspace normalization aligns with Phase 52 Color Governance."
    },
    "REMOVE_IMAGE_ALPHA": {
        fix_id: "REMOVE_IMAGE_ALPHA",
        label: "Remove image alpha",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Image alpha removal is currently not supported.",
        operator_message: "Image alpha removal is unsupported."
    },
    "REPAIR_DAMAGED_IMAGE_OBJECT": {
        fix_id: "REPAIR_DAMAGED_IMAGE_OBJECT",
        label: "Repair damaged image object",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: false,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Damaged image repair is currently not supported.",
        operator_message: "Damaged image repair is unsupported."
    },
    "VECTORIZE_BITMAP_TEXT": {
        fix_id: "VECTORIZE_BITMAP_TEXT",
        label: "Vectorize bitmap text",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "CRITICAL",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Bitmap text vectorization is currently not supported.",
        operator_message: "Bitmap text vectorization is unsupported."
    },
    "RESTORE_RASTERIZED_VECTOR": {
        fix_id: "RESTORE_RASTERIZED_VECTOR",
        label: "Restore rasterized vector",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "CRITICAL",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["EXPERIMENTAL"],
        customer_message: "Rasterized vector restoration is currently not supported.",
        operator_message: "Rasterized vector restoration is unsupported."
    },
    // Phase 65A — Selective Image Fixes
    "CONVERT_IMAGE_RGB_TO_CMYK_SELECTIVE": {
        fix_id: "CONVERT_IMAGE_RGB_TO_CMYK_SELECTIVE",
        label: "Convert RGB images to CMYK (selective)",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Selective RGB-to-CMYK image conversion may affect color appearance and requires human review.",
        operator_message: "Selective per-image RGB-to-CMYK conversion requires color-managed image stream replacement; not safely automatable without a rendering pipeline and before/after evidence. Global conversion is never performed.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "TAG_UNTAGGED_IMAGES": {
        fix_id: "TAG_UNTAGGED_IMAGES",
        label: "Tag untagged images with ICC profile",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "MEDIUM",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Tagging untagged images with a color profile may affect color interpretation and requires human review.",
        operator_message: "Assigning an ICC profile to an untagged image changes how its color values are interpreted; cannot be safely inferred without source/intent evidence.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "NORMALIZE_IMAGE_ICC_PROFILE": {
        fix_id: "NORMALIZE_IMAGE_ICC_PROFILE",
        label: "Normalize image ICC profile",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "HIGH",
        requires_human_review: true,
        production_safe: false,
        destructive: true,
        visually_sensitive: true,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Image ICC profile normalization may affect color appearance and requires human review.",
        operator_message: "Replacing or remapping an embedded ICC profile changes color rendering; requires color-managed pipeline and visual verification not currently available.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    },
    "FLAG_LOW_RES_IMAGES_UNFIXABLE": {
        fix_id: "FLAG_LOW_RES_IMAGES_UNFIXABLE",
        label: "Flag low resolution images as unfixable",
        category: "image_quality",
        implemented: false,
        detectable: true,
        autofixable: false,
        risk_level: "LOW",
        requires_human_review: true,
        production_safe: false,
        destructive: false,
        visually_sensitive: false,
        toolchain: [],
        supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
        customer_message: "Low-resolution images have been flagged for review; resolution cannot be safely improved automatically.",
        operator_message: "Detection/flagging only — automatic upscaling would invent detail and is never performed. Source assets or customer approval are required to resolve.",
        evidence_required: true,
        compliance_claim_allowed: false,
        production_certified: false,
        review_required: true
    }
};

function getFixCapability(fixId) {
    return REGISTRY[fixId] || null;
}

function listFixCapabilities() {
    return Object.values(REGISTRY);
}

function isFixImplemented(fixId) {
    const cap = REGISTRY[fixId];
    return cap ? cap.implemented : false;
}

function isFixAutofixable(fixId, policyMode = "SAFE") {
    const cap = REGISTRY[fixId];
    if (!cap || !cap.implemented || !cap.autofixable) return false;
    return cap.supported_modes.includes(policyMode);
}

function normalizeFixId(fixId) {
    if (REGISTRY[fixId]) return fixId;
    
    // Fallback normalizations for legacy codes
    const map = {
        'BLEED_MISSING': 'APPLY_BLEED',
        'COLOR_PROFILE_MISMATCH': 'CONVERT_CMYK',
        'TRANSPARENCY_PRESENT': 'FLATTEN_TRANSPARENCY',
        'TRIMBOX_MISSING': 'REBUILD_TRIMBOX',
        'TRIMBOX_INVALID': 'REBUILD_TRIMBOX',
        'TRIMBOX_OUTSIDE_MEDIABOX': 'REBUILD_TRIMBOX',
        'GEOM_TRIMBOX_MISSING': 'REBUILD_TRIMBOX',
        'TRIM_BOX_ANOMALY': 'REBUILD_TRIMBOX',
        'BLEEDBOX_MISSING': 'APPLY_BLEED',
        'IND_COLOR_001': 'CONVERT_CMYK',
        'IND_COLOR_002': 'INJECT_OUTPUT_INTENT',
        'IND_COLOR_006': 'INJECT_OUTPUT_INTENT',
        'IND_GEOM_001': 'APPLY_BLEED',
        'IND_GEOM_002': 'APPLY_BLEED',
        'IND_GEOM_003': 'REBUILD_TRIMBOX',
        'COLOR_RGB_OBJECTS_DETECTED': 'CONVERT_CMYK',
        'COLOR_ICC_PROFILE_MISSING': 'INJECT_OUTPUT_INTENT',
        'COLOR_MIXED_COLOR_SPACES': 'CONVERT_CMYK',
        'COLOR_OUTPUT_INTENT_MISSING': 'INJECT_OUTPUT_INTENT',
        // Font finding mappings (these map to their respective fix capabilities, though the fixes are unimplemented)
        'NON_EMBEDDED_FONTS': 'EMBED_FONTS',
        'TYPE3_FONTS': 'OUTLINE_TYPE3_FONTS',
        'MISSING_GLYPHS': 'FLAG_MISSING_GLYPHS_UNFIXABLE',
        'FONT_SUBSTITUTION_RISK': 'REPLACE_MISSING_FONTS',
        // Phase 66A — Engine Font Fixes finding mappings
        'FONTS_NOT_EMBEDDED': 'EMBED_FONTS',
        'IND_FONT_001': 'EMBED_FONTS',
        'FONT_SUBSET': 'SUBSET_EMBEDDED_FONTS',
        'IND_FONT_002': 'SUBSET_EMBEDDED_FONTS',
        'TYPE3_FONTS_PRESENT': 'OUTLINE_TYPE3_FONTS',
        'IND_FONT_003': 'OUTLINE_TYPE3_FONTS',
        'IND_FONT_004': 'FLAG_MISSING_GLYPHS_UNFIXABLE',
        'FONT_ENCODING_INVALID': 'REPAIR_FONT_ENCODING',
        'IND_FONT_005': 'REPAIR_FONT_ENCODING'
    };
    
    return map[fixId] || fixId;
}

module.exports = {
    REGISTRY,
    getFixCapability,
    listFixCapabilities,
    isFixImplemented,
    isFixAutofixable,
    normalizeFixId
};
